### PR TITLE
Fixes the case that OSX can have spaces in it's paths too

### PR DESCRIPTION
**Pull request by CWRau**

### CODE REVIEW

**Comment by codearoni** [comment]
Interesting. I figured OSX would escape things properly. 

@CWRau have a stack trace of the error you experienced that spawned this PR?

Also paging @LazyChild : is this an issue you experienced on OSX?

**Comment by CWRau** [comment]
```
{ Error: Command failed: /Users/Jenkins/workspace/InDesign Plugin Trunk/subProject/node_modules/zxp-provider/bin/osx/ZXPSignCmd -sign tmpBuild2/subProject ./out/InDesign_Plugin_1.1.1.zxp ./certFile certPW 
/bin/sh: /Users/Jenkins/workspace/InDesign: No such file or directory

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/Users/Jenkins/workspace/InDesign Plugin Trunk/subProject/node_modules/zxp-provider/bin/osx/ZXPSignCmd -sign tmpBuild2/subProject ./out/InDesign_Plugin_1.1.1.zxp ./certFile certPW ' }
{ Error: Command failed: /Users/Jenkins/workspace/InDesign Plugin Trunk/subProject/node_modules/zxp-provider/bin/osx/ZXPSignCmd -sign tmpBuild2/subProject ./out/InDesign_Plugin_1.1.1.zxp ./certFile certPW 
/bin/sh: /Users/Jenkins/workspace/InDesign: No such file or directory

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/Users/Jenkins/workspace/InDesign Plugin Trunk/subProject/node_modules/zxp-provider/bin/osx/ZXPSignCmd -sign tmpBuild2/subProject ./out/InDesign_Plugin_1.1.1.zxp ./certFile certPW ' }
[17:16:59] 'build' errored after 10 s
[17:16:59] Error: Command failed: /Users/Jenkins/workspace/InDesign Plugin Trunk/subProject/node_modules/zxp-provider/bin/osx/ZXPSignCmd -sign tmpBuild2/subProject ./out/InDesign_Plugin_1.1.1.zxp ./certFile certPW 
/bin/sh: /Users/Jenkins/workspace/InDesign: No such file or directory

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! subProject@1.1.1 release: `gulp --gulpfile ./gulpfile.js build --force=true --release=true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the subProject@1.1.1 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jenkins/.npm/_logs/2018-01-31T16_16_59_918Z-debug.log
```

**Comment by codearoni** [comment]
alright @CWRau I'll push this as a patch release. My grad school chair would be distraught I encouraged spaces in paths, but there's nothing technically wrong with this change. I fixed it for windows due to the way Program Files is defined. You def don't need spaces in paths on OSX but ¯\_(ツ)_/¯

patch release 1.1.4

**Comment by CWRau** [comment]
Yeah, I don't like spaces in paths either, but sometimes we cannot decide on that 😞

**Pull request merged**
